name: powersoul_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  supabase_flutter: ^2.12.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
